includes:
  - configs/sim2real/base.yml

model:
  name: dqn
  run_model: True
  epsilon_decay: 0.99 # original: 0.99
  epsilon_min: 0.01 # original: 0.01
  grad_clip: 0.5
  one_hot: True
  phase: True
  graphic: True

trainer:
  learning_start: 1000
  buffer_size: 5000